// Minimal OpenAPI 3.1 document describing the v1 surface.
export function openApiDocument() {
  const paths: Record<string, unknown> = {};
  const def = (summary: string, tags: string[], auth = true, body = false) => ({
    summary,
    tags,
    ...(auth ? { security: [{ bearerAuth: [] }] } : {}),
    ...(body ? { requestBody: { content: { 'application/json': { schema: { type: 'object' } } } } } : {}),
    responses: {
      '200': { description: 'Success', content: { 'application/json': { schema: { $ref: '#/components/schemas/Success' } } } },
      '400': { description: 'Validation error', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
      '401': { description: 'Unauthorized' },
      '403': { description: 'Forbidden / tenant denied' },
    },
  });
  const routes: [string, string, string, string[]][] = [
    ['/auth/register', 'post', 'Register', ['auth']],
    ['/auth/login', 'post', 'Login (supports ?cookie=1 for httpOnly refresh)', ['auth']],
    ['/auth/refresh', 'post', 'Refresh session (body token or httpOnly cookie)', ['auth']],
    ['/auth/logout', 'post', 'Logout', ['auth']],
    ['/auth/me', 'get', 'Current user', ['auth']],
    ['/auth/sessions', 'get', 'List active sessions', ['auth']],
    ['/auth/password/change', 'post', 'Change password', ['auth']],
    ['/users', 'get', 'List users', ['users']],
    ['/users', 'post', 'Create user', ['users']],
    ['/users/me/permissions', 'get', 'My permissions for an organization', ['users']],
    ['/organizations', 'get', 'List organizations', ['organizations']],
    ['/organizations', 'post', 'Create organization', ['organizations']],
    ['/organizations/{id}/branding', 'get', 'Public branding subset (white-label)', ['organizations']],
    ['/permissions', 'get', 'Permission catalog', ['rbac']],
    ['/roles', 'get', 'Roles with permissions', ['rbac']],
    ['/roles/{role}/permissions', 'put', 'Remap role permissions (super_admin)', ['rbac']],
    ['/auth/verify-status', 'get', 'Email verification status', ['auth']],
    ['/auth/verify-email/request', 'post', 'Re-send verification (throttled)', ['auth']],
    ['/courses', 'get', 'List courses', ['courses']],
    ['/courses', 'post', 'Create course', ['courses']],
    ['/courses/{id}/sections', 'get', 'List sections', ['courses']],
    ['/courses/sections/{sectionId}/lessons', 'get', 'List lessons', ['courses']],
    ['/enrollments', 'post', 'Enroll in course', ['courses']],
    ['/quizzes', 'post', 'Create quiz', ['assessment']],
    ['/quizzes', 'get', 'List quizzes for a course', ['assessment']],
    ['/quizzes/{id}/questions', 'get', 'List questions (correctness hidden for students)', ['assessment']],
    ['/quiz-attempts/{attemptId}/submit', 'post', 'Submit answers (idempotent)', ['assessment']],
    ['/quiz-attempts/{attemptId}/grade', 'post', 'Manual grading', ['assessment']],
    ['/assignments', 'post', 'Create assignment', ['assessment']],
    ['/assignments/{id}/submissions', 'post', 'Submit assignment (idempotent)', ['assessment']],
    ['/grades', 'post', 'Record grade', ['assessment']],
    ['/attendance/sessions', 'post', 'Create attendance session', ['attendance']],
    ['/attendance/records', 'post', 'Record attendance', ['attendance']],
    ['/certificates/verify/{number}', 'get', 'Verify certificate (public)', ['certificates']],
    ['/certificates/issue', 'post', 'Issue certificate', ['certificates']],
    ['/announcements', 'get', 'List announcements', ['social']],
    ['/discussions', 'get', 'List threads', ['social']],
    ['/files', 'get', 'List files', ['storage']],
    ['/uploads', 'post', 'Upload file', ['storage']],
    ['/search', 'get', 'Org-scoped search', ['search']],
    ['/reports/organization-summary', 'get', 'Organization summary', ['reports']],
    ['/reports/completion', 'get', 'Completion per course', ['reports']],
    ['/reports/quiz-performance', 'get', 'Quiz performance', ['reports']],
    ['/reports/attendance', 'get', 'Attendance summary', ['reports']],
    ['/reports/student-progress', 'get', 'Student progress detail', ['reports']],
    ['/notifications', 'get', 'My notifications', ['notifications']],
    ['/push/subscriptions', 'post', 'Register push subscription (needs VAPID keys)', ['notifications']],
    ['/settings', 'get', 'Global settings (super_admin)', ['settings']],
    ['/setup', 'post', 'First-run setup (locked afterwards)', ['settings']],
    ['/audit-logs', 'get', 'Audit logs', ['settings']],
    ['/course-tags', 'get', 'Course tags', ['authoring']],
    ['/courses/{id}/prerequisites', 'get', 'Course prerequisites', ['authoring']],
    ['/courses/{id}/drip', 'get', 'Drip rules', ['authoring']],
    ['/courses/{id}/waitlist', 'get', 'Waitlist', ['authoring']],
    ['/courses/{id}/duplicate', 'post', 'Duplicate course (structure only)', ['authoring']],
    ['/courses/{id}/versions', 'get', 'Version history', ['authoring']],
    ['/courses/{id}/request-approval', 'post', 'Request publish approval', ['authoring']],
    ['/publish-approvals', 'get', 'Pending approvals', ['authoring']],
    ['/courses/export', 'get', 'Export courses CSV', ['authoring']],
    ['/question-banks', 'get', 'Question banks', ['assessment']],
    ['/quiz-attempts/{attemptId}/autosave', 'put', 'Autosave answers', ['assessment']],
    ['/cohorts', 'get', 'Cohorts', ['cohorts']],
    ['/programs', 'get', 'Programs/paths', ['cohorts']],
    ['/competencies/student', 'get', 'Competency evidence', ['cohorts']],
    ['/live-sessions', 'get', 'Live sessions', ['live']],
    ['/bundles', 'get', 'Bundles', ['commerce']],
    ['/coupons', 'post', 'Create coupon', ['commerce']],
    ['/orders', 'get', 'Orders', ['commerce']],
    ['/orders/{id}/refund', 'post', 'Refund order', ['commerce']],
    ['/payments/webhooks/{provider}', 'post', 'Signed payment webhook', ['commerce']],
    ['/affiliates', 'post', 'Create affiliate', ['commerce']],
    ['/gifts/redeem', 'post', 'Redeem gift', ['commerce']],
    ['/commissions', 'get', 'Commissions', ['commerce']],
    ['/commerce/revenue', 'get', 'Revenue report', ['reports']],
    ['/scorm/upload', 'post', 'Import SCORM 1.2 package', ['scorm']],
    ['/scorm/attempts', 'post', 'Start/resume SCORM attempt', ['scorm']],
    ['/ai/jobs', 'post', 'AI draft job (review-gated)', ['ai']],
    ['/exercises', 'get', 'Coding exercises', ['exercises']],
    ['/email/queue', 'get', 'Email queue', ['notifications']],
    ['/invitations', 'post', 'Invite user', ['users']],
    ['/imports', 'post', 'CSV import (dry-run capable)', ['imports']],
    ['/reports/engagement', 'get', 'Engagement analytics', ['reports']],
    ['/reports/export', 'get', 'CSV export', ['reports']],
    ['/catalog/courses', 'get', 'Public course catalog', ['catalog']],
    ['/catalog/bundles/{id}', 'get', 'Public bundle detail', ['catalog']],
  ];
  for (const [p, method, summary, tags] of routes) {
    const isPublic =
      p.includes('verify') ||
      p.includes('branding') ||
      p.startsWith('/catalog/') ||
      ['/auth/register', '/auth/login', '/auth/refresh', '/setup'].some((pub) => p === pub || p.startsWith(`${pub}/`));
    paths[`/api/v1${p}`] = { [method]: def(summary, tags, !isPublic, method === 'post') };
  }
  return {
    openapi: '3.1.0',
    info: { title: 'LMS Headless API', version: '1.0.0', description: 'Headless LMS REST API (Hono + D1). Base path /api/v1.' },
    servers: [{ url: '/api/v1' }],
    components: {
      securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
      schemas: {
        Success: { type: 'object', properties: { success: { type: 'boolean' }, data: {}, meta: { type: 'object' } }, required: ['success', 'data'] },
        Error: { type: 'object', properties: { success: { type: 'boolean' }, error: { type: 'object', properties: { code: { type: 'string' }, message: { type: 'string' }, details: {} } } }, required: ['success', 'error'] },
      },
    },
    paths,
  };
}
